### PR TITLE
Fix compatability with K8s v1.20

### PR DESCRIPTION
**Pull request by optix2000**
And also update other plugins

See #7

### CODE REVIEW

**Comment by chrislusf** [comment]
Thanks for your PR!

I added a fix https://github.com/seaweedfs/seaweedfs-csi-driver/commit/0ddc866b7f897f01f7f7c9888c80c7f0a7dba24e based on your changes. Please help to verify it.

**Comment by optix2000** [comment]
Still getting the same `DeadlineExceeded` error as described in #7. Still not sure what the provisioner is trying to talk to and timing out on.

```
% kubectl -n kube-system logs csi-seaweedfs-controller-0 csi-provisioner
I0111 22:17:16.138169       1 csi-provisioner.go:121] Version: v2.0.4
I0111 22:17:16.139197       1 csi-provisioner.go:135] Building kube configs for running in cluster...
I0111 22:17:16.177674       1 connection.go:153] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0111 22:17:26.177917       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I0111 22:17:30.090535       1 common.go:111] Probing CSI driver for readiness
I0111 22:17:30.090577       1 connection.go:182] GRPC call: /csi.v1.Identity/Probe
I0111 22:17:30.090591       1 connection.go:183] GRPC request: {}
I0111 22:17:30.097236       1 connection.go:185] GRPC response: {}
I0111 22:17:30.097381       1 connection.go:186] GRPC error: <nil>
I0111 22:17:30.097402       1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
I0111 22:17:30.097408       1 connection.go:183] GRPC request: {}
I0111 22:17:30.098403       1 connection.go:185] GRPC response: {"name":"seaweedfs-csi-driver","vendor_version":"1.0.0"}
I0111 22:17:30.098497       1 connection.go:186] GRPC error: <nil>
I0111 22:17:30.098515       1 csi-provisioner.go:182] Detected CSI driver seaweedfs-csi-driver
W0111 22:17:30.098522       1 metrics.go:333] metrics endpoint will not be started because `metrics-address` was not specified.
I0111 22:17:30.098534       1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0111 22:17:30.098539       1 connection.go:183] GRPC request: {}
I0111 22:17:30.099535       1 connection.go:185] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
I0111 22:17:30.099964       1 connection.go:186] GRPC error: <nil>
I0111 22:17:30.100095       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0111 22:17:30.100174       1 connection.go:183] GRPC request: {}
I0111 22:17:30.101334       1 connection.go:185] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]}
I0111 22:17:30.101588       1 connection.go:186] GRPC error: <nil>
I0111 22:17:30.102450       1 csi-provisioner.go:207] CSI driver supports PUBLISH_UNPUBLISH_VOLUME, watching VolumeAttachments
I0111 22:17:30.104231       1 controller.go:735] Using saving PVs to API server in background
I0111 22:17:30.205009       1 controller.go:820] Starting provisioner controller seaweedfs-csi-driver_csi-seaweedfs-controller-0_7904b489-d6d5-40ac-b538-8a0a9a569154!
I0111 22:17:30.205132       1 volume_store.go:97] Starting save volume queue
I0111 22:17:30.306084       1 controller.go:869] Started provisioner controller seaweedfs-csi-driver_csi-seaweedfs-controller-0_7904b489-d6d5-40ac-b538-8a0a9a569154!
I0111 22:17:30.306307       1 controller.go:1317] provision "default/test-pvc" class "seaweedfs-storage": started
I0111 22:17:30.306417       1 controller.go:573] CreateVolumeRequest {Name:pvc-07df5d84-c18d-431f-bf31-d2b42f08c7e4 CapacityRange:required_bytes:1073741824  VolumeCapabilities:[mount:<> access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0111 22:17:30.308063       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0111 22:17:30.308078       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-07df5d84-c18d-431f-bf31-d2b42f08c7e4","volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":1}}]}
I0111 22:17:30.313829       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-pvc", UID:"07df5d84-c18d-431f-bf31-d2b42f08c7e4", APIVersion:"v1", ResourceVersion:"38634195", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test-pvc"
I0111 22:17:40.308327       1 connection.go:185] GRPC response: {}
I0111 22:17:40.308556       1 connection.go:186] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0111 22:17:40.308606       1 controller.go:645] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Background: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0111 22:17:40.308678       1 controller.go:1091] Temporary error received, adding PVC 07df5d84-c18d-431f-bf31-d2b42f08c7e4 to claims in progress
W0111 22:17:40.308713       1 controller.go:943] Retrying syncing claim "07df5d84-c18d-431f-bf31-d2b42f08c7e4", failure 0
E0111 22:17:40.308764       1 controller.go:966] error syncing claim "07df5d84-c18d-431f-bf31-d2b42f08c7e4": failed to provision volume with StorageClass "seaweedfs-storage": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0111 22:17:40.308806       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-pvc", UID:"07df5d84-c18d-431f-bf31-d2b42f08c7e4", APIVersion:"v1", ResourceVersion:"38634195", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "seaweedfs-storage": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0111 22:17:41.309046       1 controller.go:1317] provision "default/test-pvc" class "seaweedfs-storage": started
I0111 22:17:41.310199       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-pvc", UID:"07df5d84-c18d-431f-bf31-d2b42f08c7e4", APIVersion:"v1", ResourceVersion:"38634195", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test-pvc"
I0111 22:17:41.310405       1 controller.go:573] CreateVolumeRequest {Name:pvc-07df5d84-c18d-431f-bf31-d2b42f08c7e4 CapacityRange:required_bytes:1073741824  VolumeCapabilities:[mount:<> access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0111 22:17:41.310639       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0111 22:17:41.310647       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-07df5d84-c18d-431f-bf31-d2b42f08c7e4","volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":1}}]}
I0111 22:17:51.311082       1 connection.go:185] GRPC response: {}
I0111 22:17:51.311207       1 connection.go:186] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0111 22:17:51.311251       1 controller.go:645] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Background: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0111 22:17:51.311326       1 controller.go:1091] Temporary error received, adding PVC 07df5d84-c18d-431f-bf31-d2b42f08c7e4 to claims in progress
```

**Comment by chrislusf** [comment]
can not tell. maybe the seaweedfs cluster was not running?

**Comment by optix2000** [comment]
Running and accessible from the seaweedfs-csi-plugin. Is there any way of increasing verbosity on the csi-plugin?
```
% kubectl -n kube-system exec -it csi-seaweedfs-controller-0 -c seaweedfs-csi-plugin -- /bin/sh
/ # wget -O - $SEAWEEDFS_FILER | head -n10
Connecting to seaweedfs.seaweedfs.svc.cluster.local:8888 (10.43.110.54:8888)
writing to stdout
<!DOCTYPE html>
<html>
<head>
  <title>SeaweedFS Filer</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/seaweedfsstatic/bootstrap/3.3.1/css/bootstrap.min.css">
<style>
body { padding-bottom: 128px; }
#drop-area {
  border: 1px transparent;
-                    100% |************************************************************************|  3145  0:00:00 ETA
written to stdout
```

**Comment by chrislusf** [comment]
try to use `kubectl logs`

```
kubectl logs csi-seaweedfs-controller-0 -n kube-system -c csi-attacher

kubectl logs csi-seaweedfs-node-9fzj7 -n kube-system -c csi-seaweedfs-plugin

```

**Comment by optix2000** [comment]
Like I mentioned in #7, there's nothing interesting in any of the other pod logs.

```
% kubectl -n kube-system logs daemonset/csi-seaweedfs-node csi-seaweedfs-plugin                                                                                                            :(
I0111 22:17:13     1 driver.go:44] Driver: seaweedfs-csi-driver version: 1.0.0
I0111 22:17:13     1 driver.go:90] Enabling volume access mode: SINGLE_NODE_WRITER
I0111 22:17:13     1 driver.go:90] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I0111 22:17:13     1 driver.go:101] Enabling controller service capability: CREATE_DELETE_VOLUME
I0111 22:17:13     1 driver.go:101] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0111 22:17:13     1 server.go:92] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
```
```
% kubectl -n kube-system logs csi-seaweedfs-controller-0 csi-attacher                                                                                                                    :(
I0111 22:17:19.280548       1 main.go:91] Version: v3.0.2
I0111 22:17:19.283995       1 connection.go:153] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
W0111 22:17:29.284188       1 connection.go:172] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I0111 22:17:29.971435       1 common.go:111] Probing CSI driver for readiness
I0111 22:17:29.975554       1 main.go:136] CSI driver name: "seaweedfs-csi-driver"
W0111 22:17:29.975631       1 metrics.go:333] metrics endpoint will not be started because `metrics-address` was not specified.
I0111 22:17:29.979413       1 main.go:162] CSI driver supports ControllerPublishUnpublish, using real CSI handler
I0111 22:17:29.982044       1 controller.go:121] Starting CSI attacher
I0111 22:17:29.982458       1 reflector.go:207] Starting reflector *v1.PersistentVolume (10m0s) from k8s.io/client-go/informers/factory.go:134
I0111 22:17:29.982501       1 reflector.go:243] Listing and watching *v1.PersistentVolume from k8s.io/client-go/informers/factory.go:134
I0111 22:17:29.982557       1 reflector.go:207] Starting reflector *v1.VolumeAttachment (10m0s) from k8s.io/client-go/informers/factory.go:134
I0111 22:17:29.982567       1 reflector.go:243] Listing and watching *v1.VolumeAttachment from k8s.io/client-go/informers/factory.go:134
I0111 22:17:29.983337       1 reflector.go:207] Starting reflector *v1.CSINode (10m0s) from k8s.io/client-go/informers/factory.go:134
I0111 22:17:29.983368       1 reflector.go:243] Listing and watching *v1.CSINode from k8s.io/client-go/informers/factory.go:134
I0111 22:17:30.082246       1 shared_informer.go:270] caches populated
I0111 22:25:31.034174       1 reflector.go:515] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.VolumeAttachment total 0 items received
I0111 22:25:49.039674       1 reflector.go:515] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.PersistentVolume total 0 items received
I0111 22:27:12.035632       1 reflector.go:515] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.CSINode total 0 items received
I0111 22:27:30.036390       1 reflector.go:369] k8s.io/client-go/informers/factory.go:134: forcing resync
I0111 22:27:30.038252       1 reflector.go:369] k8s.io/client-go/informers/factory.go:134: forcing resync
I0111 22:32:42.037534       1 reflector.go:515] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.VolumeAttachment total 0 items received
I0111 22:32:56.043955       1 reflector.go:515] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.PersistentVolume total 0 items received
I0111 22:35:38.038085       1 reflector.go:515] k8s.io/client-go/informers/factory.go:134: Watch close - *v1.CSINode total 0 items received
I0111 22:37:30.036869       1 reflector.go:369] k8s.io/client-go/informers/factory.go:134: forcing resync
I0111 22:37:30.038806       1 reflector.go:369] k8s.io/client-go/informers/factory.go:134: forcing resync
...repeated every few min
```

**Comment by chrislusf** [comment]
Also, what is your kubernetes version? Try to upgrade first.

**Comment by chrislusf** [comment]
make sure the `seaweedfs-csi.yaml` has the correct SEAWEEDFS_FILER value in 2 places.

**Comment by chrislusf** [comment]
this may be related. Wrong filer address caused the symptom. 

https://github.com/seaweedfs/seaweedfs-csi-driver/issues/10#issuecomment-759170157

**Comment by optix2000** [comment]
> Running and accessible from the seaweedfs-csi-plugin. Is there any way of increasing verbosity on the csi-plugin?
> 
> ```
> % kubectl -n kube-system exec -it csi-seaweedfs-controller-0 -c seaweedfs-csi-plugin -- /bin/sh
> / # wget -O - $SEAWEEDFS_FILER | head -n10
> Connecting to seaweedfs.seaweedfs.svc.cluster.local:8888 (10.43.110.54:8888)
> writing to stdout
> <!DOCTYPE html>
> <html>
> <head>
>   <title>SeaweedFS Filer</title>
>   <meta name="viewport" content="width=device-width, initial-scale=1">
>   <link rel="stylesheet" href="/seaweedfsstatic/bootstrap/3.3.1/css/bootstrap.min.css">
> <style>
> body { padding-bottom: 128px; }
> #drop-area {
>   border: 1px transparent;
> -                    100% |************************************************************************|  3145  0:00:00 ETA
> written to stdout
> ```

Filer is correct and accessible from the controller pod

```
% kubectl -n kube-system exec -it -c csi-seaweedfs-plugin daemonset/csi-seaweedfs-node -- sh
/ # wget -O - $SEAWEEDFS_FILER | head -n10
Connecting to seaweedfs.seaweedfs.svc.cluster.local:8888 (10.43.110.54:8888)
writing to stdout
-                    100% |************************************************************************|  3145  0:00:00 ETA
written to stdout
<!DOCTYPE html>
<html>
<head>
  <title>SeaweedFS Filer</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/seaweedfsstatic/bootstrap/3.3.1/css/bootstrap.min.css">
<style>
body { padding-bottom: 128px; }
#drop-area {
  border: 1px transparent;
/ #
```

And is also accessible from the node driver pod

**Comment by chrislusf** [comment]
how did you configure the `seaweedfs-csi.yaml`?

**Comment by optix2000** [comment]
```
# On the latest commit
% git rev-parse HEAD
5c89ac3f8846a8373b2c503e867df8d0b70501e7
```
I'm just finding and replacing the seaweedfs filer address with my own.
```diff
% git diff
diff --git a/deploy/kubernetes/seaweedfs-csi.yaml b/deploy/kubernetes/seaweedfs-csi.yaml
index 5ad1c01..31574ef 100644
--- a/deploy/kubernetes/seaweedfs-csi.yaml
+++ b/deploy/kubernetes/seaweedfs-csi.yaml
@@ -301,7 +301,7 @@ spec:
             - name: CSI_ENDPOINT
               value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
             - name: SEAWEEDFS_FILER
-              value: "192.168.2.7:8888" # host and port of your SeaweedFs filer
+              value: "seaweedfs.seaweedfs.svc.cluster.local:8888" # host and port of your SeaweedFs filer
             - name: NODE_ID
               valueFrom:
                 fieldRef:
@@ -369,7 +369,7 @@ spec:
             - name: CSI_ENDPOINT
               value: unix:///csi/csi.sock
             - name: SEAWEEDFS_FILER
-              value: "192.168.2.7:8888" # host and port of your SeaweedFs filer, could also be K8S DNS entry like seaweedfs-filer.seaweed-namespace.svc:8888
+              value: "seaweedfs.seaweedfs.svc.cluster.local:8888" # host and port of your SeaweedFs filer, could also be K8S DNS entry like seaweedfs-filer.seaweed-namespace.svc:8888
             - name: NODE_ID
               valueFrom:
                 fieldRef:
```

The filer is being started as a single node for testing on the same machine via k8s.
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: seaweedfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-master
  namespace: seaweedfs
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: seaweedfs
      seaweedfs-type: master
  template:
    metadata:
      labels:
        app: seaweedfs
        seaweedfs-type: master
    spec:
      containers:
      - name: seaweed-master
        image: chrislusf/seaweedfs
        args: ["server", "-dir=/mnt", "-s3"]
        volumeMounts:
          - mountPath: /mnt
            name: fs
        ports:
        - containerPort: 9333 # Master
        - containerPort: 8080 # Volume
        - containerPort: 8888 # Filer
      volumes:
        - name: fs
          hostPath:
            path: /storage
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  namespace: seaweedfs
  labels:
    app: seaweedfs
spec:
  selector:
    app: seaweedfs
  ports:
    - protocol: TCP
      port: 9333
      name: master
    - protocol: TCP
      port: 8080
      name: volume
    - protocol: TCP
      port: 8888
      name: filer
```

**Comment by chrislusf** [comment]
Seems ok but I suspect there are issues with host names. K8s DNS has its problems. Can you try to access a SeaweedFS cluster outside of the current K8s?

**Comment by optix2000** [comment]
> > Running and accessible from the seaweedfs-csi-plugin. Is there any way of increasing verbosity on the csi-plugin?
> > ```
> > % kubectl -n kube-system exec -it csi-seaweedfs-controller-0 -c seaweedfs-csi-plugin -- /bin/sh
> > / # wget -O - $SEAWEEDFS_FILER | head -n10
> > Connecting to seaweedfs.seaweedfs.svc.cluster.local:8888 (10.43.110.54:8888)
> > writing to stdout
> > <!DOCTYPE html>
> > <html>
> > <head>
> >   <title>SeaweedFS Filer</title>
> >   <meta name="viewport" content="width=device-width, initial-scale=1">
> >   <link rel="stylesheet" href="/seaweedfsstatic/bootstrap/3.3.1/css/bootstrap.min.css">
> > <style>
> > body { padding-bottom: 128px; }
> > #drop-area {
> >   border: 1px transparent;
> > -                    100% |************************************************************************|  3145  0:00:00 ETA
> > written to stdout
> > ```
> 
> Filer is correct and accessible from the controller pod
> 
> ```
> % kubectl -n kube-system exec -it -c csi-seaweedfs-plugin daemonset/csi-seaweedfs-node -- sh
> / # wget -O - $SEAWEEDFS_FILER | head -n10
> Connecting to seaweedfs.seaweedfs.svc.cluster.local:8888 (10.43.110.54:8888)
> writing to stdout
> -                    100% |************************************************************************|  3145  0:00:00 ETA
> written to stdout
> <!DOCTYPE html>
> <html>
> <head>
>   <title>SeaweedFS Filer</title>
>   <meta name="viewport" content="width=device-width, initial-scale=1">
>   <link rel="stylesheet" href="/seaweedfsstatic/bootstrap/3.3.1/css/bootstrap.min.css">
> <style>
> body { padding-bottom: 128px; }
> #drop-area {
>   border: 1px transparent;
> / #
> ```
> 
> And is also accessible from the node driver pod

Again if you read the above logs, the names are resolvable and accessible from _within_ the k8s pod running the driver and the logs clearly show that seaweedfs is up and running.

- The `wget` is running within the seaweedfs-csi-plugin (pay attention to the `kubectl` command).
- The `wget` is using the same environment variable (`SEAWEEDFS_FILER`) that the CSI is supposed to use ([according to your k8s manifest](https://github.com/seaweedfs/seaweedfs-csi-driver/blob/master/deploy/kubernetes/seaweedfs-csi.yaml#L298)).
- The `wget` responds with the [seaweedfs filer UI](https://github.com/chrislusf/seaweedfs/blob/eb32af25d43729d0430abb30d91b80dc718b4dcf/weed/server/filer_ui/templates.go#L24) which shows the filer is accessible.

Thus I don't believe it's an issue with DNS or networking like you're alluding to. Even *if* it was DNS or networking related, there are *no* logs that indicate that the name is not resolvable (ie name or service not known, etc), or the network is not accessible (ie timouts, connection reset/refused, no route to host, etc)

**Comment by chrislusf** [comment]
Can you try to access a SeaweedFS cluster outside of the current K8s?

**Comment by chrislusf** [comment]
Closing since no more updates.

**Pull request closed without merging**
