### PR TITLE
image: Provide a better built container image

### PR DESCRIPTION
**Pull request by cmacrae**
Hey @chrislusf 👋 Another contribution for you here :)  
These changes provide a more declarative and efficient approach to building the container image

### CODE REVIEW

**Comment by chrislusf** [comment]
Thanks for your idea! But this change has hard coded url to download the weed binary, not easy to maintain.

**Comment by cmacrae** [comment]
Yep, a fair thing to point out :)
I suppose there's a trade-off between maintainability and declaration/reproducibility.

But, I certainly agree - given the frequency at which you release updates to SeaweedFS, it would be a pain to maintain.

I'm out at the moment, but when I'm back at a computer, I'll update this PR to simply grab the latest 😁

**Comment by cmacrae** [comment]
Ah, also just to point out: the GitHub Actions Docker build failed because the step interpolated the gut reference as the tag (28/merge), which is invalid format.

I'll raise another PR to fix that :)

**Comment by chrislusf** [comment]
Current build process seems fine, and efficient enough?

**Comment by cmacrae** [comment]
Personally, I feel these changes are improvements. You're re-compiling the `weed` binary when it's already built and generally available. Also, cloning the repo from within the Dockerfile to build is a bit of an anti-pattern - as you're not building the source tree that is currently checked out, but rather the one that has been pushed to the main branch

These are just my opinions though :)

**Comment by cmacrae** [comment]
With the above in place and the pipeline fixed, it means you get CI builds on each PR, too - to ensure contributions don't break the build (or any tests) :)

**Pull request merged**
